"""Initial tables

Revision ID: a2e45941cf3c
Revises: 
Create Date: 2025-05-30 19:14:19.110136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e45941cf3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.Enum('M', 'F', 'O', name='gender', native_enum=False), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('death_date', sa.Date(), nullable=True),
    sa.Column('birth_place', sa.String(length=100), nullable=True),
    sa.Column('alive', sa.Boolean(), nullable=False),
    sa.Column('last_update', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_person_id', sa.Uuid(), nullable=False),
    sa.Column('to_person_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.Enum('BIOLOGICAL_PARENT', 'ADOPTIVE_PARENT', 'STEP_PARENT', 'SPOUSE', 'SIBLING', 'HALF_SIBLING', 'AUNT_UNCLE', 'COUSIN', 'GODPARENT', 'BIOLOGICAL_CHILD', 'ADOPTIVE_CHILD', 'STEP_CHILD', 'NIECE_NEPHEW', 'GODCHILD', name='relationshiptype', native_enum=False, length=20), nullable=False),
    sa.ForeignKeyConstraint(['from_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['to_person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationships')
    op.drop_table('persons')
    # ### end Alembic commands ###
